# Generated by Django 5.2.16 on 2026-07-30 11:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('upcoming', 'À venir'), ('active', 'Actif'), ('paused', 'En pause'), ('completed', 'Terminé'), ('archived', 'Archivé')], default='upcoming', max_length=20, verbose_name='statut')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('critical', 'Critique')], default='normal', max_length=20, verbose_name='priorité')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='date de début')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='échéance')),
                ('color', models.CharField(default='#315efb', max_length=7, verbose_name='couleur')),
                ('estimated_load', models.PositiveIntegerField(blank=True, null=True, verbose_name='charge estimée en minutes')),
                ('notes', models.TextField(blank=True, verbose_name='contexte ou notes générales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archivé le')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projets',
                'ordering': ('-priority', 'deadline', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MacroActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('todo', 'À faire'), ('in_progress', 'En cours'), ('waiting', 'En attente'), ('completed', 'Terminée'), ('cancelled', 'Abandonnée')], default='todo', max_length=20, verbose_name='statut')),
                ('priority', models.CharField(blank=True, choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('critical', 'Critique')], max_length=20, verbose_name='priorité')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='date de début')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='échéance')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macro_activities', to='projects.project', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'macro-activité',
                'verbose_name_plural': 'macro-activités',
                'ordering': ('display_order', 'created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('deadline__isnull', True), ('deadline__gte', models.F('start_date')), _connector='OR'), name='project_deadline_after_start'),
        ),
        migrations.AddConstraint(
            model_name='macroactivity',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('deadline__isnull', True), ('deadline__gte', models.F('start_date')), _connector='OR'), name='macro_activity_deadline_after_start'),
        ),
    ]
