# Generated by Django 5.2.16 on 2026-07-30 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('todo', 'À faire'), ('in_progress', 'En cours'), ('waiting', 'En attente'), ('completed', 'Terminée'), ('cancelled', 'Abandonnée')], default='todo', max_length=20, verbose_name='statut')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('critical', 'Critique')], default='normal', max_length=20, verbose_name='priorité')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='date de début')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='date planifiée')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='échéance')),
                ('estimated_load', models.PositiveIntegerField(blank=True, null=True, verbose_name='charge estimée en minutes')),
                ('origin', models.CharField(choices=[('manual', 'Saisie manuelle'), ('inbox', 'Boîte de réception'), ('meeting', 'Réunion'), ('other', 'Autre')], default='manual', max_length=20, verbose_name='origine')),
                ('waiting_for', models.CharField(blank=True, max_length=200, verbose_name='personne ou entité attendue')),
                ('waiting_comment', models.TextField(blank=True, verbose_name="commentaire d'attente")),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='réalisée le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
                ('macro_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.macroactivity', verbose_name='macro-activité')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'tâche',
                'verbose_name_plural': 'tâches',
                'ordering': ('deadline', 'planned_date', '-priority', 'created_at'),
            },
        ),
    ]
