# Generated by Django 5.2.16 on 2026-07-30 12:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200, verbose_name='titre ou contenu')),
                ('status', models.CharField(choices=[('to_process', 'À qualifier'), ('converted', 'Transformé en tâche'), ('ignored', 'Ignoré'), ('archived', 'Archivé')], default='to_process', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='traité le')),
                ('converted_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_inbox_item', to='tasks.task', verbose_name='tâche créée')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_items', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'verbose_name': 'élément de boîte de réception',
                'verbose_name_plural': 'éléments de boîte de réception',
                'ordering': ('-created_at',),
            },
        ),
    ]
