apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-projet-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestion-projet-pro
  template:
    metadata:
      labels:
        app: gestion-projet-pro
    spec:
      initContainers:
        - name: migrate
          image: ghcr.io/hdkaramoko/gestion-projet-pro:0.1.0
          imagePullPolicy: IfNotPresent
          command:
            - /app/.venv/bin/python
            - manage.py
            - migrate
            - --noinput
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: config.settings.production

            - name: DB_ENGINE
              value: postgresql

          envFrom:
            - secretRef:
                name: gestion-projet-secrets

      containers:
        - name: gestion-projet-pro
          image: ghcr.io/hdkaramoko/gestion-projet-pro:0.1.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          env:
            - name: DJANGO_SETTINGS_MODULE
              value: config.settings.production

            - name: DB_ENGINE
              value: postgresql

            - name: HOME
              value: /tmp

            - name: XDG_CACHE_HOME
              value: /tmp/.cache

            - name: UV_CACHE_DIR
              value: /tmp/uv-cache

          envFrom:
            - secretRef:
                name: gestion-projet-secrets

          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi

          readinessProbe:
            httpGet:
              path: /
              port: 8000
              httpHeaders:
                - name: Host
                  value: gestion-projet-pro
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 8000
              httpHeaders:
                - name: Host
                  value: gestion-projet-pro
            initialDelaySeconds: 30
            periodSeconds: 20
