# Generated by Django 5.2.16 on 2026-07-30 13:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('scheduled_at', models.DateTimeField(verbose_name='date et heure')),
                ('participants', models.TextField(blank=True, verbose_name='participants')),
                ('context', models.TextField(blank=True, verbose_name='contexte')),
                ('discussion_points', models.TextField(blank=True, verbose_name='points discutés')),
                ('decisions', models.TextField(blank=True, verbose_name='décisions prises')),
                ('next_steps', models.TextField(blank=True, verbose_name='prochaines étapes')),
                ('notes', models.TextField(blank=True, verbose_name='notes complémentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='projects.project', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'réunion',
                'verbose_name_plural': 'réunions',
                'ordering': ('-scheduled_at',),
            },
        ),
        migrations.CreateModel(
            name='MeetingAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='intitulé')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('assignee', models.CharField(blank=True, max_length=200, verbose_name='responsable')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='échéance')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('critical', 'Critique')], default='normal', max_length=20, verbose_name='priorité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('created_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_meeting_action', to='tasks.task', verbose_name='tâche créée')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='meetings.meeting', verbose_name='réunion')),
            ],
            options={
                'verbose_name': 'action de réunion',
                'verbose_name_plural': 'actions de réunion',
                'ordering': ('created_at',),
            },
        ),
    ]
